import type { CropfortRole } from "@/types/cropfort";
import type {
  AdminOrganization,
  AdminUser,
  AssetOwner,
  FarmArea,
  FarmBlockRef,
  RateCardLine,
  VendorRecord,
} from "@/types/cropfort-modules";
import { computeVariance } from "./variance";

function line(
  partial: Omit<RateCardLine, "variancePct" | "flagged" | "createdAt" | "updatedAt"> & {
    createdAt?: string;
  }
): RateCardLine {
  const v = computeVariance(partial);
  const createdAt = partial.createdAt ?? "2026-03-12T08:00:00.000Z";
  return {
    ...partial,
    variancePct: v.variancePct,
    flagged: v.flagged,
    createdAt,
    updatedAt: createdAt,
  };
}

export const SEED_RATE_CARD: RateCardLine[] = [
  line({
    id: "rc-01",
    resourceCode: "LAB-PRUNE",
    resourceName: "Pruning labour",
    category: "labour",
    unitOfMeasure: "person-day",
    rateBirr: 450,
    benchmarkFarmARate: 420,
    benchmarkFarmBRate: 440,
    justificationNote: "",
    status: "approved",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: "2026-01-01",
    effectiveTo: "2026-12-31",
  }),
  line({
    id: "rc-02",
    resourceCode: "LAB-PICK",
    resourceName: "Cherry picking",
    category: "labour",
    unitOfMeasure: "kg",
    rateBirr: 18.5,
    benchmarkFarmARate: 17,
    benchmarkFarmBRate: 19,
    justificationNote: "",
    status: "approved",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: "2026-01-01",
    effectiveTo: "2026-12-31",
  }),
  line({
    id: "rc-03",
    resourceCode: "LAB-WEED",
    resourceName: "Weeding crew",
    category: "labour",
    unitOfMeasure: "person-day",
    rateBirr: 380,
    benchmarkFarmARate: 360,
    benchmarkFarmBRate: 370,
    justificationNote: "",
    status: "submitted",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: "2026-04-01",
    effectiveTo: null,
  }),
  line({
    id: "rc-04",
    resourceCode: "MAT-NPK",
    resourceName: "NPK 15-15-15",
    category: "material",
    unitOfMeasure: "kg",
    rateBirr: 62,
    benchmarkFarmARate: 48,
    benchmarkFarmBRate: 50,
    justificationNote: "Jimma wholesale shortage Q1; three quotes on file.",
    status: "submitted",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: "2026-03-01",
    effectiveTo: null,
  }),
  line({
    id: "rc-05",
    resourceCode: "MAT-UREA",
    resourceName: "Urea",
    category: "material",
    unitOfMeasure: "kg",
    rateBirr: 54,
    benchmarkFarmARate: 52,
    benchmarkFarmBRate: 55,
    justificationNote: "",
    status: "draft",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: null,
    effectiveTo: null,
  }),
  line({
    id: "rc-06",
    resourceCode: "MAT-LIME",
    resourceName: "Agricultural lime",
    category: "material",
    unitOfMeasure: "t",
    rateBirr: 4200,
    benchmarkFarmARate: 3900,
    benchmarkFarmBRate: 4100,
    justificationNote: "",
    status: "draft",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: null,
    effectiveTo: null,
  }),
  line({
    id: "rc-07",
    resourceCode: "MAC-TRACT",
    resourceName: "Tractor hire 75hp",
    category: "machinery",
    unitOfMeasure: "hour",
    rateBirr: 1850,
    benchmarkFarmARate: 1400,
    benchmarkFarmBRate: 1450,
    justificationNote: "",
    status: "draft",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: "2026-06-01",
    effectiveTo: null,
  }),
  line({
    id: "rc-08",
    resourceCode: "MAC-SPRAY",
    resourceName: "Knapsack sprayer hire",
    category: "machinery",
    unitOfMeasure: "day",
    rateBirr: 95,
    benchmarkFarmARate: 90,
    benchmarkFarmBRate: 100,
    justificationNote: "",
    status: "approved",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: "2026-01-01",
    effectiveTo: "2026-12-31",
  }),
  line({
    id: "rc-09",
    resourceCode: "TRN-CHERRY",
    resourceName: "Cherry haulage to mill",
    category: "transport",
    unitOfMeasure: "t-km",
    rateBirr: 12.4,
    benchmarkFarmARate: 11.8,
    benchmarkFarmBRate: 12.1,
    justificationNote: "",
    status: "approved",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: "2026-01-01",
    effectiveTo: "2026-12-31",
  }),
  line({
    id: "rc-10",
    resourceCode: "TRN-FERT",
    resourceName: "Fertiliser inbound",
    category: "transport",
    unitOfMeasure: "t",
    rateBirr: 2800,
    benchmarkFarmARate: 2100,
    benchmarkFarmBRate: 2200,
    justificationNote: "Fuel spike; SPX to re-quote after harvest.",
    status: "returned",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: null,
    effectiveTo: null,
  }),
  line({
    id: "rc-11",
    resourceCode: "LAB-SHADE",
    resourceName: "Shade tree planting",
    category: "labour",
    unitOfMeasure: "person-day",
    rateBirr: 410,
    benchmarkFarmARate: 400,
    benchmarkFarmBRate: 405,
    justificationNote: "",
    status: "draft",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: null,
    effectiveTo: null,
  }),
  line({
    id: "rc-12",
    resourceCode: "MAT-SEED",
    resourceName: "Coffee seedling (stumped)",
    category: "material",
    unitOfMeasure: "each",
    rateBirr: 18,
    benchmarkFarmARate: 16,
    benchmarkFarmBRate: 17,
    justificationNote: "",
    status: "submitted",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: "2026-05-01",
    effectiveTo: null,
  }),
  line({
    id: "rc-13",
    resourceCode: "MAT-MULCH",
    resourceName: "Organic mulch",
    category: "material",
    unitOfMeasure: "m³",
    rateBirr: 340,
    benchmarkFarmARate: 330,
    benchmarkFarmBRate: 350,
    justificationNote: "",
    status: "approved",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: "2026-01-01",
    effectiveTo: "2026-12-31",
  }),
  line({
    id: "rc-14",
    resourceCode: "MAC-PUMP",
    resourceName: "Irrigation pump hire",
    category: "machinery",
    unitOfMeasure: "day",
    rateBirr: 620,
    benchmarkFarmARate: 480,
    benchmarkFarmBRate: 500,
    justificationNote: "Only certified diesel unit available in Jimma this season.",
    status: "submitted",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: "2026-04-15",
    effectiveTo: "2026-10-31",
  }),
  line({
    id: "rc-15",
    resourceCode: "OTH-GUARD",
    resourceName: "Night security",
    category: "other",
    unitOfMeasure: "person-night",
    rateBirr: 220,
    benchmarkFarmARate: 210,
    benchmarkFarmBRate: 230,
    justificationNote: "",
    status: "approved",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: "2026-01-01",
    effectiveTo: "2026-12-31",
  }),
  line({
    id: "rc-16",
    resourceCode: "LAB-STUMP",
    resourceName: "Stumping crew",
    category: "labour",
    unitOfMeasure: "ha",
    rateBirr: 9800,
    benchmarkFarmARate: 7200,
    benchmarkFarmBRate: 7500,
    justificationNote: "",
    status: "draft",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: null,
    effectiveTo: null,
  }),
  line({
    id: "rc-17",
    resourceCode: "MAT-HERB",
    resourceName: "Glyphosate 48%",
    category: "material",
    unitOfMeasure: "L",
    rateBirr: 410,
    benchmarkFarmARate: 395,
    benchmarkFarmBRate: 405,
    justificationNote: "",
    status: "draft",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: null,
    effectiveTo: null,
  }),
  line({
    id: "rc-18",
    resourceCode: "TRN-LABOUR",
    resourceName: "Crew bus (estate loop)",
    category: "transport",
    unitOfMeasure: "day",
    rateBirr: 2400,
    benchmarkFarmARate: 2300,
    benchmarkFarmBRate: 2500,
    justificationNote: "",
    status: "approved",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: "2026-01-01",
    effectiveTo: "2026-12-31",
  }),
  line({
    id: "rc-19",
    resourceCode: "MAC-MILL",
    resourceName: "Mobile mill hire",
    category: "machinery",
    unitOfMeasure: "day",
    rateBirr: 12500,
    benchmarkFarmARate: 11000,
    benchmarkFarmBRate: 11800,
    justificationNote: "Includes operator and fuel; two quotes attached.",
    status: "submitted",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: "2026-10-01",
    effectiveTo: "2026-12-31",
  }),
  line({
    id: "rc-20",
    resourceCode: "OTH-TRAIN",
    resourceName: "GAP training facilitator",
    category: "other",
    unitOfMeasure: "day",
    rateBirr: 3500,
    benchmarkFarmARate: 3200,
    benchmarkFarmBRate: 3400,
    justificationNote: "",
    status: "returned",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: null,
    effectiveTo: null,
  }),
  line({
    id: "rc-21",
    resourceCode: "LAB-NURSE",
    resourceName: "Nursery attendant",
    category: "labour",
    unitOfMeasure: "person-month",
    rateBirr: 6800,
    benchmarkFarmARate: 6500,
    benchmarkFarmBRate: 6700,
    justificationNote: "",
    status: "approved",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: "2026-01-01",
    effectiveTo: "2026-12-31",
  }),
  line({
    id: "rc-22",
    resourceCode: "MAT-BAG",
    resourceName: "GrainPro bag 69kg",
    category: "material",
    unitOfMeasure: "each",
    rateBirr: 95,
    benchmarkFarmARate: 88,
    benchmarkFarmBRate: 90,
    justificationNote: "Imported lot; FX already absorbed in Birr quote.",
    status: "draft",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: null,
    effectiveTo: null,
  }),
  line({
    id: "rc-23",
    resourceCode: "TRN-PARCH",
    resourceName: "Parchment to warehouse",
    category: "transport",
    unitOfMeasure: "t",
    rateBirr: 1950,
    benchmarkFarmARate: 1900,
    benchmarkFarmBRate: 2000,
    justificationNote: "",
    status: "submitted",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: "2026-11-01",
    effectiveTo: null,
  }),
  line({
    id: "rc-24",
    resourceCode: "MAC-DRIER",
    resourceName: "Raised-bed timber kit",
    category: "machinery",
    unitOfMeasure: "set",
    rateBirr: 8400,
    benchmarkFarmARate: 6100,
    benchmarkFarmBRate: 6400,
    justificationNote: "Treated eucalyptus; local mill quote only.",
    status: "draft",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: null,
    effectiveTo: null,
  }),
  line({
    id: "rc-25",
    resourceCode: "OTH-SOIL",
    resourceName: "Soil lab panel",
    category: "other",
    unitOfMeasure: "sample",
    rateBirr: 780,
    benchmarkFarmARate: 750,
    benchmarkFarmBRate: 800,
    justificationNote: "",
    status: "approved",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: "2026-01-01",
    effectiveTo: "2026-12-31",
  }),
  line({
    id: "rc-26",
    resourceCode: "LAB-COMP",
    resourceName: "Compost turning",
    category: "labour",
    unitOfMeasure: "person-day",
    rateBirr: 360,
    benchmarkFarmARate: 350,
    benchmarkFarmBRate: 365,
    justificationNote: "",
    status: "draft",
    budgetYear: 2025,
    archivedAt: null,
    effectiveFrom: null,
    effectiveTo: null,
  }),
];

const ROLES = {
  fs: "field_supervisor" as CropfortRole,
  bo: "bagro_office" as CropfortRole,
  sv: "spx_validator" as CropfortRole,
  fo: "farm_owner" as CropfortRole,
  pa: "spx_platform_admin" as CropfortRole,
};

const TENANT_SHECHA = { tenantId: "tenant-shecha", tenantName: "Shecha Estate" };
const TENANT_CHAKA = { tenantId: "tenant-chaka", tenantName: "Chaka Buna Estate" };
const TENANT_GOMA = { tenantId: "tenant-goma", tenantName: "Goma South" };

function user(partial: AdminUser): AdminUser {
  return partial;
}

export const SEED_USERS: AdminUser[] = [
  user({
    id: "u-01",
    name: "Platform Admin",
    email: "admin@cropfort.example",
    organization: "spx",
    roles: [ROLES.pa],
    tenants: [{ ...TENANT_SHECHA, roles: [ROLES.pa], blockIds: [] }],
    status: "active",
    createdAt: "2025-11-02T09:00:00.000Z",
    lastLoginAt: "2026-09-14T07:12:00.000Z",
    neverLoggedIn: false,
  }),
  user({
    id: "u-02",
    name: "Daniel Okello",
    email: "daniel@spx.example",
    organization: "spx",
    roles: [ROLES.sv],
    tenants: [
      { ...TENANT_SHECHA, roles: [ROLES.sv], blockIds: [] },
      { ...TENANT_CHAKA, roles: [ROLES.sv], blockIds: [] },
    ],
    status: "active",
    createdAt: "2025-12-01T10:00:00.000Z",
    lastLoginAt: "2026-09-15T06:40:00.000Z",
    neverLoggedIn: false,
  }),
  user({
    id: "u-03",
    name: "Helena Silva",
    email: "helena@silva.example",
    organization: "silva",
    roles: [ROLES.fo],
    tenants: [{ ...TENANT_SHECHA, roles: [ROLES.fo], blockIds: [] }],
    status: "active",
    createdAt: "2025-12-04T11:00:00.000Z",
    lastLoginAt: "2026-09-10T14:22:00.000Z",
    neverLoggedIn: false,
  }),
  user({
    id: "u-04",
    name: "Sara Mengistu",
    email: "sara@bagro.example",
    organization: "bagro",
    roles: [ROLES.bo],
    tenants: [{ ...TENANT_SHECHA, roles: [ROLES.bo], blockIds: [] }],
    status: "active",
    createdAt: "2026-01-08T08:00:00.000Z",
    lastLoginAt: "2026-09-14T16:01:00.000Z",
    neverLoggedIn: false,
  }),
  user({
    id: "u-05",
    name: "Abebe Bekele",
    email: "abebe@bagro.example",
    organization: "bagro",
    roles: [ROLES.fs],
    tenants: [{ ...TENANT_SHECHA, roles: [ROLES.fs], blockIds: ["blk-a1", "blk-a2"] }],
    status: "active",
    createdAt: "2026-01-09T08:00:00.000Z",
    lastLoginAt: "2026-09-13T05:18:00.000Z",
    neverLoggedIn: false,
  }),
  user({
    id: "u-06",
    name: "Marta Tadesse",
    email: "marta@spx.example",
    organization: "spx",
    roles: [ROLES.sv],
    tenants: [{ ...TENANT_GOMA, roles: [ROLES.sv], blockIds: [] }],
    status: "invited",
    createdAt: "2026-09-01T09:00:00.000Z",
    lastLoginAt: null,
    neverLoggedIn: true,
  }),
  user({
    id: "u-07",
    name: "Yonas Hailu",
    email: "yonas@bagro.example",
    organization: "bagro",
    roles: [ROLES.fs],
    tenants: [{ ...TENANT_CHAKA, roles: [ROLES.fs], blockIds: ["blk-c1"] }],
    status: "suspended",
    createdAt: "2026-02-14T09:00:00.000Z",
    lastLoginAt: "2026-06-02T11:00:00.000Z",
    neverLoggedIn: false,
  }),
  user({
    id: "u-08",
    name: "Lulit Assefa",
    email: "lulit@silva.example",
    organization: "silva",
    roles: [ROLES.fo],
    tenants: [{ ...TENANT_CHAKA, roles: [ROLES.fo], blockIds: [] }],
    status: "active",
    createdAt: "2026-02-20T09:00:00.000Z",
    lastLoginAt: "2026-09-08T09:40:00.000Z",
    neverLoggedIn: false,
  }),
  user({
    id: "u-09",
    name: "Kedir Mohammed",
    email: "kedir@bagro.example",
    organization: "bagro",
    roles: [ROLES.bo, ROLES.fs],
    tenants: [{ ...TENANT_GOMA, roles: [ROLES.bo], blockIds: [] }],
    status: "active",
    createdAt: "2026-03-01T09:00:00.000Z",
    lastLoginAt: "2026-09-12T12:00:00.000Z",
    neverLoggedIn: false,
  }),
  user({
    id: "u-10",
    name: "Naomi Clarke",
    email: "naomi@spx.example",
    organization: "spx",
    roles: [ROLES.pa, ROLES.sv],
    tenants: [
      { ...TENANT_SHECHA, roles: [ROLES.sv], blockIds: [] },
      { ...TENANT_CHAKA, roles: [ROLES.sv], blockIds: [] },
      { ...TENANT_GOMA, roles: [ROLES.sv], blockIds: [] },
    ],
    status: "active",
    createdAt: "2026-03-11T09:00:00.000Z",
    lastLoginAt: "2026-09-15T08:02:00.000Z",
    neverLoggedIn: false,
  }),
  user({
    id: "u-11",
    name: "Tesfaye Worku",
    email: "tesfaye@bagro.example",
    organization: "bagro",
    roles: [ROLES.fs],
    tenants: [{ ...TENANT_SHECHA, roles: [ROLES.fs], blockIds: ["blk-b1"] }],
    status: "invited",
    createdAt: "2026-08-22T09:00:00.000Z",
    lastLoginAt: null,
    neverLoggedIn: true,
  }),
  user({
    id: "u-12",
    name: "Rahel Getachew",
    email: "rahel@bagro.example",
    organization: "bagro",
    roles: [ROLES.bo],
    tenants: [{ ...TENANT_CHAKA, roles: [ROLES.bo], blockIds: [] }],
    status: "active",
    createdAt: "2026-04-02T09:00:00.000Z",
    lastLoginAt: "2026-09-11T15:33:00.000Z",
    neverLoggedIn: false,
  }),
  user({
    id: "u-13",
    name: "Samuel Desta",
    email: "samuel@spx.example",
    organization: "spx",
    roles: [ROLES.sv],
    tenants: [{ ...TENANT_SHECHA, roles: [ROLES.sv], blockIds: [] }],
    status: "suspended",
    createdAt: "2026-01-20T09:00:00.000Z",
    lastLoginAt: "2026-05-01T10:00:00.000Z",
    neverLoggedIn: false,
  }),
  user({
    id: "u-14",
    name: "Isabel Silva",
    email: "isabel@silva.example",
    organization: "silva",
    roles: [ROLES.fo],
    tenants: [{ ...TENANT_GOMA, roles: [ROLES.fo], blockIds: [] }],
    status: "invited",
    createdAt: "2026-09-05T09:00:00.000Z",
    lastLoginAt: null,
    neverLoggedIn: true,
  }),
  user({
    id: "u-15",
    name: "Binyam Alemu",
    email: "binyam@bagro.example",
    organization: "bagro",
    roles: [ROLES.fs],
    tenants: [{ ...TENANT_GOMA, roles: [ROLES.fs], blockIds: ["blk-g1", "blk-g2"] }],
    status: "active",
    createdAt: "2026-04-18T09:00:00.000Z",
    lastLoginAt: "2026-09-14T04:50:00.000Z",
    neverLoggedIn: false,
  }),
  user({
    id: "u-16",
    name: "Helen Desta",
    email: "helen@spx.example",
    organization: "spx",
    roles: [ROLES.sv],
    tenants: [{ ...TENANT_CHAKA, roles: [ROLES.sv], blockIds: [] }],
    status: "active",
    createdAt: "2026-05-03T09:00:00.000Z",
    lastLoginAt: "2026-09-09T18:00:00.000Z",
    neverLoggedIn: false,
  }),
  user({
    id: "u-17",
    name: "Mulugeta Bekele",
    email: "mulugeta@bagro.example",
    organization: "bagro",
    roles: [ROLES.bo],
    tenants: [{ ...TENANT_GOMA, roles: [ROLES.bo], blockIds: [] }],
    status: "active",
    createdAt: "2026-05-20T09:00:00.000Z",
    lastLoginAt: "2026-09-07T11:11:00.000Z",
    neverLoggedIn: false,
  }),
  user({
    id: "u-18",
    name: "Chaltu Haji",
    email: "chaltu@bagro.example",
    organization: "bagro",
    roles: [ROLES.fs],
    tenants: [{ ...TENANT_CHAKA, roles: [ROLES.fs], blockIds: ["blk-c2"] }],
    status: "active",
    createdAt: "2026-06-01T09:00:00.000Z",
    lastLoginAt: "2026-09-13T07:07:00.000Z",
    neverLoggedIn: false,
  }),
  user({
    id: "u-19",
    name: "Peter Lang",
    email: "peter@spx.example",
    organization: "spx",
    roles: [ROLES.pa],
    tenants: [{ ...TENANT_SHECHA, roles: [ROLES.pa], blockIds: [] }],
    status: "invited",
    createdAt: "2026-09-10T09:00:00.000Z",
    lastLoginAt: null,
    neverLoggedIn: true,
  }),
  user({
    id: "u-20",
    name: "Sofia Mendes",
    email: "sofia@silva.example",
    organization: "silva",
    roles: [ROLES.fo],
    tenants: [
      { ...TENANT_SHECHA, roles: [ROLES.fo], blockIds: [] },
      { ...TENANT_CHAKA, roles: [ROLES.fo], blockIds: [] },
    ],
    status: "active",
    createdAt: "2026-06-12T09:00:00.000Z",
    lastLoginAt: "2026-09-02T19:20:00.000Z",
    neverLoggedIn: false,
  }),
  user({
    id: "u-21",
    name: "Getu Lemma",
    email: "getu@bagro.example",
    organization: "bagro",
    roles: [ROLES.fs],
    tenants: [{ ...TENANT_SHECHA, roles: [ROLES.fs], blockIds: ["blk-a3"] }],
    status: "suspended",
    createdAt: "2026-02-01T09:00:00.000Z",
    lastLoginAt: "2026-04-20T08:00:00.000Z",
    neverLoggedIn: false,
  }),
  user({
    id: "u-22",
    name: "Amina Yusuf",
    email: "amina@bagro.example",
    organization: "bagro",
    roles: [ROLES.bo],
    tenants: [{ ...TENANT_SHECHA, roles: [ROLES.bo], blockIds: [] }],
    status: "active",
    createdAt: "2026-07-01T09:00:00.000Z",
    lastLoginAt: "2026-09-14T13:45:00.000Z",
    neverLoggedIn: false,
  }),
  user({
    id: "u-23",
    name: "Jonah Reed",
    email: "jonah@spx.example",
    organization: "spx",
    roles: [ROLES.sv],
    tenants: [{ ...TENANT_GOMA, roles: [ROLES.sv], blockIds: [] }],
    status: "active",
    createdAt: "2026-07-18T09:00:00.000Z",
    lastLoginAt: "2026-09-06T10:10:00.000Z",
    neverLoggedIn: false,
  }),
  user({
    id: "u-24",
    name: "Hana Bekele",
    email: "hana@bagro.example",
    organization: "bagro",
    roles: [ROLES.fs],
    tenants: [{ ...TENANT_GOMA, roles: [ROLES.fs], blockIds: ["blk-g3"] }],
    status: "invited",
    createdAt: "2026-09-12T09:00:00.000Z",
    lastLoginAt: null,
    neverLoggedIn: true,
  }),
];

export const SEED_BLOCKS: FarmBlockRef[] = [
  { id: "blk-a1", code: "SH-A1", name: "Shecha Upper East", hectares: 18.4 },
  { id: "blk-a2", code: "SH-A2", name: "Shecha Ridge", hectares: 22.1 },
  { id: "blk-a3", code: "SH-A3", name: "Shecha River", hectares: 16.8 },
  { id: "blk-b1", code: "SH-B1", name: "Shecha Nursery", hectares: 4.2 },
  { id: "blk-c1", code: "CK-C1", name: "Chaka North", hectares: 31.0 },
  { id: "blk-c2", code: "CK-C2", name: "Chaka Valley", hectares: 27.5 },
  { id: "blk-g1", code: "GM-G1", name: "Goma Bench", hectares: 19.0 },
  { id: "blk-g2", code: "GM-G2", name: "Goma Shade", hectares: 14.6 },
  { id: "blk-g3", code: "GM-G3", name: "Goma West", hectares: 21.3 },
  { id: "blk-k1", code: "KF-K1", name: "Kefa Trial", hectares: 8.0 },
  { id: "blk-l1", code: "LM-L1", name: "Limu Slope", hectares: 12.5 },
  { id: "blk-s1", code: "SD-S1", name: "Sidama Plot 4", hectares: 9.7 },
];

export const SEED_ORGANIZATIONS: AdminOrganization[] = [
  { id: "org-spx", name: "SPX", type: "spx", status: "active", createdAt: "2025-10-01T00:00:00.000Z" },
  { id: "org-bagro", name: "B-Agro", type: "bagro", status: "active", createdAt: "2025-10-01T00:00:00.000Z" },
  { id: "org-silva", name: "Silva Estate Holdings", type: "silva_estate", status: "active", createdAt: "2025-10-01T00:00:00.000Z" },
  { id: "org-chaka", name: "Chaka Buna PLC", type: "silva_estate", status: "active", createdAt: "2026-01-12T00:00:00.000Z" },
  { id: "org-jimma", name: "Jimma Highlands Trust", type: "silva_estate", status: "active", createdAt: "2026-02-02T00:00:00.000Z" },
  { id: "org-kefa", name: "Kefa Works", type: "vendor_org", status: "active", createdAt: "2026-03-01T00:00:00.000Z" },
  { id: "org-sidama", name: "Sidama Labour Co-op", type: "vendor_org", status: "active", createdAt: "2026-03-08T00:00:00.000Z" },
  { id: "org-ext", name: "Extension Partners", type: "other", status: "inactive", createdAt: "2026-04-01T00:00:00.000Z" },
];

export const SEED_FARM_AREAS: FarmArea[] = [
  {
    id: "fa-shecha",
    name: "Shecha Estate",
    organizationId: "org-silva",
    totalHectares: 212,
    status: "active",
    blockIds: ["blk-a1", "blk-a2", "blk-a3", "blk-b1"],
    vendorIds: ["vnd-bagro", "vnd-kefa"],
    assetOwnerIds: ["ao-silva"],
    createdAt: "2025-11-01T00:00:00.000Z",
  },
  {
    id: "fa-chaka",
    name: "Chaka Buna Estate",
    organizationId: "org-chaka",
    totalHectares: 164,
    status: "active",
    blockIds: ["blk-c1", "blk-c2"],
    vendorIds: ["vnd-bagro", "vnd-sidama"],
    assetOwnerIds: ["ao-chaka", "ao-silva"],
    createdAt: "2026-01-15T00:00:00.000Z",
  },
  {
    id: "fa-goma",
    name: "Goma South",
    organizationId: "org-jimma",
    totalHectares: 98,
    status: "active",
    blockIds: ["blk-g1", "blk-g2", "blk-g3"],
    vendorIds: ["vnd-sidama", "vnd-haul"],
    assetOwnerIds: ["ao-jimma"],
    createdAt: "2026-02-10T00:00:00.000Z",
  },
  {
    id: "fa-kefa",
    name: "Kefa Trial Blocks",
    organizationId: "org-silva",
    totalHectares: 22,
    status: "active",
    blockIds: ["blk-k1"],
    vendorIds: ["vnd-kefa"],
    assetOwnerIds: ["ao-kefa"],
    createdAt: "2026-03-04T00:00:00.000Z",
  },
  {
    id: "fa-limu",
    name: "Limu Slope",
    organizationId: "org-jimma",
    totalHectares: 41,
    status: "active",
    blockIds: ["blk-l1"],
    vendorIds: ["vnd-haul", "vnd-mill"],
    assetOwnerIds: ["ao-limu"],
    createdAt: "2026-04-12T00:00:00.000Z",
  },
  {
    id: "fa-sidama",
    name: "Sidama Plot 4",
    organizationId: "org-chaka",
    totalHectares: 18,
    status: "inactive",
    blockIds: ["blk-s1"],
    vendorIds: ["vnd-sidama"],
    assetOwnerIds: ["ao-sidama"],
    createdAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "fa-nursery",
    name: "Central Nursery",
    organizationId: "org-silva",
    totalHectares: 6.5,
    status: "active",
    blockIds: [],
    vendorIds: ["vnd-bagro", "vnd-nursery"],
    assetOwnerIds: ["ao-silva"],
    createdAt: "2026-06-01T00:00:00.000Z",
  },
];

export const SEED_VENDORS: VendorRecord[] = [
  {
    id: "vnd-bagro",
    name: "B-Agro Operations",
    category: "Estate execution",
    status: "active",
    prequalified: true,
    insuranceOnFile: true,
    farmAreaIds: ["fa-shecha", "fa-chaka", "fa-nursery"],
    blockIds: ["blk-a1", "blk-a2", "blk-c1"],
    createdAt: "2025-11-01T00:00:00.000Z",
  },
  {
    id: "vnd-kefa",
    name: "Kefa Works",
    category: "Civil / stumping",
    status: "active",
    prequalified: true,
    insuranceOnFile: true,
    farmAreaIds: ["fa-shecha", "fa-kefa"],
    blockIds: ["blk-a3", "blk-k1"],
    createdAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "vnd-sidama",
    name: "Sidama Labour Co-op",
    category: "Seasonal labour",
    status: "active",
    prequalified: true,
    insuranceOnFile: false,
    farmAreaIds: ["fa-chaka", "fa-goma", "fa-sidama"],
    blockIds: ["blk-c2", "blk-g1"],
    createdAt: "2026-03-08T00:00:00.000Z",
  },
  {
    id: "vnd-haul",
    name: "Rift Haulage",
    category: "Transport",
    status: "pending",
    prequalified: false,
    insuranceOnFile: true,
    farmAreaIds: ["fa-goma", "fa-limu"],
    blockIds: ["blk-g3", "blk-l1"],
    createdAt: "2026-04-20T00:00:00.000Z",
  },
  {
    id: "vnd-mill",
    name: "Jimma Mobile Mill",
    category: "Processing",
    status: "active",
    prequalified: true,
    insuranceOnFile: true,
    farmAreaIds: ["fa-limu"],
    blockIds: ["blk-l1"],
    createdAt: "2026-04-22T00:00:00.000Z",
  },
  {
    id: "vnd-nursery",
    name: "Highland Nursery Supply",
    category: "Plant material",
    status: "active",
    prequalified: true,
    insuranceOnFile: true,
    farmAreaIds: ["fa-nursery"],
    blockIds: ["blk-b1"],
    createdAt: "2026-06-02T00:00:00.000Z",
  },
  {
    id: "vnd-chem",
    name: "AgroChem ET",
    category: "Inputs",
    status: "expired",
    prequalified: false,
    insuranceOnFile: false,
    farmAreaIds: ["fa-shecha"],
    blockIds: [],
    createdAt: "2025-08-01T00:00:00.000Z",
  },
  {
    id: "vnd-guard",
    name: "Nightwatch Co-op",
    category: "Security",
    status: "active",
    prequalified: true,
    insuranceOnFile: true,
    farmAreaIds: ["fa-shecha", "fa-chaka"],
    blockIds: ["blk-a1", "blk-c1"],
    createdAt: "2026-01-20T00:00:00.000Z",
  },
  {
    id: "vnd-pump",
    name: "Blue Nile Pumps",
    category: "Machinery hire",
    status: "pending",
    prequalified: false,
    insuranceOnFile: true,
    farmAreaIds: ["fa-goma"],
    blockIds: ["blk-g2"],
    createdAt: "2026-07-01T00:00:00.000Z",
  },
  {
    id: "vnd-soil",
    name: "EIAR Soil Lab",
    category: "Laboratory",
    status: "active",
    prequalified: true,
    insuranceOnFile: false,
    farmAreaIds: ["fa-shecha", "fa-limu"],
    blockIds: [],
    createdAt: "2026-02-14T00:00:00.000Z",
  },
  {
    id: "vnd-old",
    name: "Legacy Fencing Ltd",
    category: "Civil",
    status: "terminated",
    prequalified: false,
    insuranceOnFile: false,
    farmAreaIds: [],
    blockIds: [],
    createdAt: "2024-11-01T00:00:00.000Z",
  },
  {
    id: "vnd-shade",
    name: "Shade Tree Collective",
    category: "Planting",
    status: "active",
    prequalified: true,
    insuranceOnFile: true,
    farmAreaIds: ["fa-chaka", "fa-kefa"],
    blockIds: ["blk-c2", "blk-k1"],
    createdAt: "2026-05-18T00:00:00.000Z",
  },
];

export const SEED_ASSET_OWNERS: AssetOwner[] = [
  {
    id: "ao-silva",
    name: "Silva Estate Holdings",
    organizationId: "org-silva",
    contactEmail: "owners@silva.example",
    contactPhone: "+251 11 555 0100",
    farmAreaIds: ["fa-shecha", "fa-chaka", "fa-kefa", "fa-nursery"],
    blockIds: ["blk-a1", "blk-a2", "blk-a3", "blk-b1", "blk-k1"],
    createdAt: "2025-11-01T00:00:00.000Z",
  },
  {
    id: "ao-chaka",
    name: "Chaka Buna PLC",
    organizationId: "org-chaka",
    contactEmail: "land@chaka.example",
    contactPhone: "+251 47 555 0200",
    farmAreaIds: ["fa-chaka"],
    blockIds: ["blk-c1", "blk-c2"],
    createdAt: "2026-01-15T00:00:00.000Z",
  },
  {
    id: "ao-jimma",
    name: "Jimma Highlands Trust",
    organizationId: "org-jimma",
    contactEmail: "trust@jimma.example",
    contactPhone: "+251 47 555 0300",
    farmAreaIds: ["fa-goma"],
    blockIds: ["blk-g1", "blk-g2", "blk-g3"],
    createdAt: "2026-02-10T00:00:00.000Z",
  },
  {
    id: "ao-kefa",
    name: "Kefa Smallholders Assoc.",
    organizationId: null,
    contactEmail: "kefa.owners@example",
    contactPhone: null,
    farmAreaIds: ["fa-kefa"],
    blockIds: ["blk-k1"],
    createdAt: "2026-03-04T00:00:00.000Z",
  },
  {
    id: "ao-limu",
    name: "Limu Family Trust",
    organizationId: "org-jimma",
    contactEmail: "limu@jimma.example",
    contactPhone: "+251 47 555 0400",
    farmAreaIds: ["fa-limu"],
    blockIds: ["blk-l1"],
    createdAt: "2026-04-12T00:00:00.000Z",
  },
  {
    id: "ao-sidama",
    name: "Sidama Plot Holders",
    organizationId: null,
    contactEmail: null,
    contactPhone: "+251 46 555 0500",
    farmAreaIds: ["fa-sidama"],
    blockIds: ["blk-s1"],
    createdAt: "2026-05-01T00:00:00.000Z",
  },
];
